/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Lighthouse.glb -t 
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Lighthouse: THREE.Mesh
  }
  materials: {
    lambert2SG: THREE.MeshStandardMaterial
  },
  /*
  animations: GLTFAction[]
   */
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/Lighthouse.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Lighthouse.geometry} material={materials.lambert2SG} />
    </group>
  )
}

useGLTF.preload('/models/Lighthouse.glb')
